type OperatorCase = (&'static str, &'static str);

const OPERATOR_CASES: &[OperatorCase] = &[
    ("concat", r#"["@input.s", {"concat": "!"}]"#),
    ("to_string", r#"["@input.n", "to_string"]"#),
    ("trim", r#"["@input.spaced", "trim"]"#),
    ("lowercase", r#"["@input.upper", "lowercase"]"#),
    ("uppercase", r#"["@input.s", "uppercase"]"#),
    (
        "replace",
        r#"["@input.text", {"replace": ["world", "there"]}]"#,
    ),
    ("split", r#"["@input.csv", {"split": ","}]"#),
    ("pad_start", r#"["@input.pad", {"pad_start": [3, "0"]}]"#),
    ("pad_end", r#"["@input.pad", {"pad_end": [3, "0"]}]"#),
    (
        "coalesce",
        r#"["@input.missing", {"coalesce": "@input.s"}]"#,
    ),
    (
        "lookup",
        r#"["@input.lookup_rows", {"lookup": ["id", "b"]}]"#,
    ),
    (
        "lookup_first",
        r#"["@input.lookup_rows", {"lookup_first": ["id", "b"]}]"#,
    ),
    ("+", r#"["@input.n", {"+": 2}]"#),
    ("-", r#"["@input.n", {"-": 1}]"#),
    ("*", r#"["@input.n", {"*": 2}]"#),
    ("/", r#"["@input.n", {"/": 2}]"#),
    ("multiply", r#"["@input.n", {"multiply": 2}]"#),
    ("add", r#"["@input.n", {"add": 2}]"#),
    ("subtract", r#"["@input.n", {"subtract": 1}]"#),
    ("divide", r#"["@input.n", {"divide": 2}]"#),
    ("round", r#"["@input.float", {"round": 2}]"#),
    ("to_base", r#"["@input.base", {"to_base": 16}]"#),
    (
        "date_format",
        r#"["@input.date", {"date_format": "%Y/%m/%d"}]"#,
    ),
    ("to_unixtime", r#"["@input.unix", "to_unixtime"]"#),
    ("and", r#"["@input.truth", {"and": true}]"#),
    ("or", r#"["@input.falsehood", {"or": true}]"#),
    ("not", r#"["@input.falsehood", "not"]"#),
    ("==", r#"["@input.n", {"==": 3}]"#),
    ("!=", r#"["@input.n", {"!=": 4}]"#),
    ("<", r#"["@input.n", {"<": 4}]"#),
    ("<=", r#"["@input.n", {"<=": 3}]"#),
    (">", r#"["@input.n", {">": 2}]"#),
    (">=", r#"["@input.n", {">=": 3}]"#),
    ("~=", r#"["@input.s", {"~=": "^h"}]"#),
    ("eq", r#"["@input.n", {"eq": 3}]"#),
    ("ne", r#"["@input.n", {"ne": 4}]"#),
    ("lt", r#"["@input.n", {"lt": 4}]"#),
    ("lte", r#"["@input.n", {"lte": 3}]"#),
    ("gt", r#"["@input.n", {"gt": 2}]"#),
    ("gte", r#"["@input.n", {"gte": 3}]"#),
    ("match", r#"["@input.s", {"match": "^h"}]"#),
    ("merge", r#"["@input.obj", {"merge": {"b":2}}]"#),
    (
        "deep_merge",
        r#"["@input.deep_left", {"deep_merge": "@input.deep_right"}]"#,
    ),
    ("get", r#"["@input.obj", {"get": "a"}]"#),
    ("pick", r#"["@input.obj", {"pick": "a"}]"#),
    ("omit", r#"["@input.obj", {"omit": "b"}]"#),
    ("keys", r#"["@input.obj", "keys"]"#),
    ("values", r#"["@input.obj", "values"]"#),
    ("entries", r#"["@input.obj", "entries"]"#),
    ("len", r#"["@input.arr", "len"]"#),
    ("from_entries", r#"["@input.entries", "from_entries"]"#),
    (
        "object_flatten",
        r#"["@input.deep_left", "object_flatten"]"#,
    ),
    (
        "object_unflatten",
        r#"["@input.flat_obj", "object_unflatten"]"#,
    ),
    ("map", r#"["@input.arr", {"map": ["@item", {"add": 1}]}]"#),
    ("filter", r#"["@input.items", {"filter": "@item.keep"}]"#),
    (
        "flat_map",
        r#"["@input.items", {"flat_map": "@item.tags"}]"#,
    ),
    ("flatten", r#"["@input.nested", {"flatten": 2}]"#),
    ("take", r#"["@input.arr", {"take": 2}]"#),
    ("drop", r#"["@input.arr", {"drop": 1}]"#),
    ("slice", r#"["@input.arr", {"slice": [1, 3]}]"#),
    ("chunk", r#"["@input.arr", {"chunk": 2}]"#),
    ("zip", r#"["@input.arr", {"zip": "@input.arr2"}]"#),
    (
        "zip_with",
        r#"["@input.arr", {"zip_with": ["@input.arr2", "@item"]}]"#,
    ),
    ("unzip", r#"["@input.pairs", "unzip"]"#),
    (
        "group_by",
        r#"["@input.items", {"group_by": "@item.role"}]"#,
    ),
    ("key_by", r#"["@input.items", {"key_by": "@item.id"}]"#),
    (
        "partition",
        r#"["@input.items", {"partition": "@item.keep"}]"#,
    ),
    ("unique", r#"["@input.dups", "unique"]"#),
    (
        "distinct_by",
        r#"["@input.items", {"distinct_by": "@item.role"}]"#,
    ),
    ("sort_by", r#"["@input.items", {"sort_by": "@item.v"}]"#),
    ("find", r#"["@input.items", {"find": "@item.keep"}]"#),
    (
        "find_index",
        r#"["@input.items", {"find_index": "@item.keep"}]"#,
    ),
    ("index_of", r#"["@input.arr", {"index_of": 2}]"#),
    ("contains", r#"["@input.arr", {"contains": 3}]"#),
    ("sum", r#"["@input.arr", "sum"]"#),
    ("avg", r#"["@input.arr", "avg"]"#),
    ("min", r#"["@input.arr", "min"]"#),
    ("max", r#"["@input.arr", "max"]"#),
    (
        "reduce",
        r#"["@input.arr", {"reduce": [["@acc", {"+": "@item"}]]}]"#,
    ),
    (
        "fold",
        r#"["@input.arr", {"fold": [0, ["@acc", {"+": "@item"}]]}]"#,
    ),
    ("first", r#"["@input.arr", "first"]"#),
    ("last", r#"["@input.arr", "last"]"#),
    ("string", r#"["@input.n", "string"]"#),
    ("int", r#"["@input.int_text", "int"]"#),
    ("float", r#"["@input.float_text", "float"]"#),
    ("bool", r#"["@input.bool_text", "bool"]"#),
];

const EXPECTED_INVENTORY: &[&str] = &[
    "concat",
    "to_string",
    "trim",
    "lowercase",
    "uppercase",
    "replace",
    "split",
    "pad_start",
    "pad_end",
    "coalesce",
    "lookup",
    "lookup_first",
    "+",
    "-",
    "*",
    "/",
    "multiply",
    "add",
    "subtract",
    "divide",
    "round",
    "to_base",
    "date_format",
    "to_unixtime",
    "and",
    "or",
    "not",
    "==",
    "!=",
    "<",
    "<=",
    ">",
    ">=",
    "~=",
    "eq",
    "ne",
    "lt",
    "lte",
    "gt",
    "gte",
    "match",
    "merge",
    "deep_merge",
    "get",
    "pick",
    "omit",
    "keys",
    "values",
    "entries",
    "len",
    "from_entries",
    "object_flatten",
    "object_unflatten",
    "map",
    "filter",
    "flat_map",
    "flatten",
    "take",
    "drop",
    "slice",
    "chunk",
    "zip",
    "zip_with",
    "unzip",
    "group_by",
    "key_by",
    "partition",
    "unique",
    "distinct_by",
    "sort_by",
    "find",
    "find_index",
    "index_of",
    "contains",
    "sum",
    "avg",
    "min",
    "max",
    "reduce",
    "fold",
    "first",
    "last",
    "string",
    "int",
    "float",
    "bool",
];

const OPERATOR_INPUT: &str = r#"[{
    "s":"hi",
    "spaced":" hi ",
    "upper":"HI",
    "text":"hello world",
    "csv":"a,b",
    "pad":"7",
    "n":3,
    "float":1.2345,
    "base":255,
    "date":"2024-01-02 03:04:05",
    "unix":"1970-01-01T00:00:01Z",
    "truth":true,
    "falsehood":false,
    "obj":{"a":1,"b":2},
    "deep_left":{"a":1,"nested":{"x":1}},
    "deep_right":{"nested":{"y":2},"c":3},
    "flat_obj":{"a.b":1,"c":2},
    "entries":[["a",1],["b",2]],
    "arr":[1,2,3],
    "arr2":[4,5,6],
    "nested":[1,[2,[3]],4],
    "pairs":[[1,"a"],[2,"b"]],
    "dups":["a","b","a"],
    "items":[
        {"id":"a","role":"admin","keep":true,"v":2,"tags":["x"]},
        {"id":"b","role":"member","keep":false,"v":1,"tags":["y","z"]},
        {"id":"c","role":"admin","keep":true,"v":3,"tags":[]}
    ],
    "lookup_rows":[{"id":"a","value":1},{"id":"b","value":2}],
    "int_text":"42",
    "float_text":"1.5",
    "bool_text":"true"
}]"#;
