use super::super::definitions::{NO_SCOPE, op, range};
use crate::v2_operator::types::{V2OperatorMetadata, V2OperatorTrace};

pub(super) const ARITHMETIC_OPERATORS: &[V2OperatorMetadata] = &[
    op(
        "+",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "-",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "*",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "/",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "multiply",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "add",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "subtract",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "divide",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "round",
        range(0, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "to_base",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
];
