use super::super::definitions::{
    ITEM_ACC_ARG_0, ITEM_ACC_ARG_1, ITEM_ARG_0, ITEM_LAST_ARG, NO_SCOPE, op, range,
};
use crate::v2_operator::types::{V2OperatorMetadata, V2OperatorTrace};

pub(super) const ARRAY_OPERATORS: &[V2OperatorMetadata] = &[
    op(
        "map",
        range(1, Some(1)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ARG_0,
    ),
    op(
        "filter",
        range(1, Some(1)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ARG_0,
    ),
    op(
        "flat_map",
        range(1, Some(1)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ARG_0,
    ),
    op(
        "flatten",
        range(0, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "take",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "drop",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "slice",
        range(1, Some(2)),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "chunk",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "zip",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "zip_with",
        range(2, None),
        V2OperatorTrace::Delegated,
        false,
        false,
        ITEM_LAST_ARG,
    ),
    op(
        "unzip",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "group_by",
        range(1, Some(1)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ARG_0,
    ),
    op(
        "key_by",
        range(1, Some(1)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ARG_0,
    ),
    op(
        "partition",
        range(1, Some(1)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ARG_0,
    ),
    op(
        "unique",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "distinct_by",
        range(1, Some(1)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ARG_0,
    ),
    op(
        "sort_by",
        range(1, Some(2)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ARG_0,
    ),
    op(
        "find",
        range(1, Some(1)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ARG_0,
    ),
    op(
        "find_index",
        range(1, Some(1)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ARG_0,
    ),
    op(
        "index_of",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "contains",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "sum",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "avg",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "min",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "max",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "reduce",
        range(1, Some(1)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ACC_ARG_0,
    ),
    op(
        "fold",
        range(2, Some(2)),
        V2OperatorTrace::ItemLevelCollection,
        false,
        false,
        ITEM_ACC_ARG_1,
    ),
    op(
        "first",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "last",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
];
