use super::super::definitions::{NO_SCOPE, op, range};
use crate::v2_operator::types::{V2OperatorMetadata, V2OperatorTrace};

pub(super) const COMPARISON_OPERATORS: &[V2OperatorMetadata] = &[
    op(
        "==",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "!=",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "<",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "<=",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        ">",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        ">=",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "~=",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "eq",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "ne",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "lt",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "lte",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "gt",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "gte",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "match",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
];
