use super::super::definitions::{NO_SCOPE, op, range};
use crate::v2_operator::types::{V2OperatorMetadata, V2OperatorTrace};

pub(super) const JSON_OPERATORS: &[V2OperatorMetadata] = &[
    op(
        "merge",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "deep_merge",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "get",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        true,
        NO_SCOPE,
    ),
    op(
        "pick",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        false,
        true,
        NO_SCOPE,
    ),
    op(
        "omit",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        false,
        true,
        NO_SCOPE,
    ),
    op(
        "keys",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "values",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "entries",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "len",
        range(0, Some(0)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "from_entries",
        range(1, None),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "object_flatten",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "object_unflatten",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        true,
        false,
        NO_SCOPE,
    ),
    op(
        "to_typed_value",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
    op(
        "from_typed_value",
        range(1, Some(1)),
        V2OperatorTrace::EagerArgs,
        false,
        false,
        NO_SCOPE,
    ),
];
